### ISSUE TITLE
Map cave entrances/dungeon entrances/ladders

### ISSUE THREAD

**Issue by Jasper-ketelaar** [ZachHerridge/Acuity#10]
Connect the regions that these kind of objects teleport you through automatically.

**Comment by troy-lamerton** [comment]
Obstacle name:
Staircase

Obstacle begin location (x, y, z):
2519, 3430, 0

Obstacle end location (x, y, z):
2518, 3431, 1

Is the obstacle bidirectional:
Yes

Obstacle requirement(s):
None

**Comment by troy-lamerton** [comment]
Obstacle name:
Ladder

Obstacle begin location (x, y, z):
2533, 3156, 0

Obstacle end location (x, y, z):
2533, 9556, 0

Is the obstacle bidirectional:
Yes

Obstacle requirement(s):
None

Note:
Dungeon inside Tree Gnome Village

**Comment by troy-lamerton** [comment]
Obstacle name:
Staircase

Obstacle begin location (x, y, z):
3058, 3376, 0

Obstacle end location (x, y, z):
3059, 9776, 0

Is the obstacle bidirectional:
Yes

Obstacle requirement(s):
None

Note:
Falador dwarven mine, east entrance

**Comment by troy-lamerton** [comment]
This is not working when walking from a distant location to the target.
If you walk to Wizard's Tower basement from Lumbridge, it will take you directly North, instead of to the ladder that 'teleports' you there.
